---
title: "Module 7: Recommended Exercises"
author: "alexaoh"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    df_print: kable
subtitle: Statistical Learning V2021
---

```{r setup, include=FALSE}
showsolA<-TRUE
showsolB<-TRUE
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=68),tidy=TRUE)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE,message=FALSE,warning=FALSE,strip.white=TRUE,prompt=FALSE,
                      cache=TRUE, size="scriptsize", comment = "#>")
```

## Problem 1

```{r}
library(ISLR)
# extract only the two variables from Auto
ds = Auto[c("horsepower","mpg")]
n = nrow(ds)
#which degrees we will look at
deg = 1:4
set.seed(1)
#training ids for training set
tr = sample.int(n = n, size = n/2)
# plot of training data
plot(ds[tr,], col = "darkgrey", main = "Polynomial regression")

colors <- rainbow(n = length(deg))

MSE = sapply(deg, function(d){
  fit <- lm(mpg~poly(horsepower, d), data = ds[tr, ])
  lines(sort(ds[tr, 1]), fit$fit[order(ds[tr, 1])], col = colors[d])
  return (mean((predict(fit, ds[-tr, ]) - ds[-tr, 2])^2))
})
legend("topright", legend=paste("d = ", deg), col = colors, lty = 1)

# Plot MSE
plot(MSE, type = "o", xlab= "Pol. Deg.", main = "Test Error (MSE)")
```

## Problem 2

```{r}
library(ggplot2)
attach(Auto)
fit2 <- lm(mpg~factor(origin))
dframe <- data.frame(origin = as.factor(sort(unique(origin))))
pred <-  predict(fit2, dframe, se = T)

# Data frame including CI (z_alpha/2 = 1.96).
dat <-  data.frame(origin = dframe, mpg = pred$fit, lwr = pred$fit - 1.96 * pred$se.fit, 
    upr = pred$fit + 1.96 * pred$se.fit)

# Plot the fitted/predicted values and CI
ggplot(dat, aes(x = origin, y = mpg)) + geom_point() + geom_segment(aes(x = origin, 
    y = lwr, xend = origin, yend = upr)) + scale_x_discrete(labels = c(`1` = "1.American", 
    `2` = "2.European", `3` = "3.Japanese"))
```

## Problem 3

Now, let us look at the `Wage` data set. The section on Additive Models [(slides 28-34 in the pdf)](https://github.com/stefaniemuff/statlearning/blob/master/7BeyondLinear/7slides.pdf) explains how we can create an AM by adding components together. One component we saw is a natural spline in `year` with one knot. Derive the expression for the design matrix $\mathbf X_2$ from the natural spline basis:
$$
b_1(x_i) = x_i, \quad b_{k+2}(x_i) = d_k(x_i)-d_K(x_i),\; k = 0, \ldots, K - 1,\\
$$
$$
d_k(x_i) = \frac{(x_i-c_k)^3_+-(x_i-c_{K+1})^3_+}{c_{K+1}-c_k}.
$$

## Problem 4

Continuation of Problem 3. 

```{r}
attach(Wage)
```
